### ISSUE TITLE
Add Immersive Engineering

### ISSUE THREAD

**Issue by Sans1the1skeleton** [HopsandBarley/For-Science-#13]
I love the mod pack but I´d like to have this mod because it adds some weapons like the revolver and you have to make them using different types of machines, also I am playing this mod pack with some friends in a server and we are trying to survive and if one dies it´s the end for that persone, the objetive is to kill the other two player but we only have the minecraft weapons for that and it isn´t easy to get the weapons in this pack because it requires a lot of materials that are hard to get in this mod pack, I´ve already played with the Immersive Engineering mod in single player and it´s really hard to get everything for the mod, I really hope you still update the mod pack because it´s awesome.

**Comment by HopsandBarley** [comment]
I really enjoy Immersive Engineering. But because it's so popular, and has been in so many packs over the years, I wanted to try and make a pack without Immersive Engineering.  At this point, I don't have any intention to add IE to the pack. 

I do plan on adding to the pack as I find mods that I feel fit with the pack.  By no means is this pack 'finished'. 

Really glad that you like it regardless. Thanks for the feedback!
